CREATE TABLE T_EXAMINATION
(
 	ID bigint NOT NULL PRIMARY KEY,
  STUDENT_ID BIGINT NOT NULL,
  EXAM_TMEPLATE_ID BIGINT NOT NULL,
  START_TIME DATE,
	END_TIME DATE,
	LIMIT_START_TIME DATE,
	LIMIT_END_TIME DATE,
	LOGIC_START_TIME DATE,
	LOGIC_END_TIME DATE,
	CODING_START_TIME DATE,
	CODING_END_TIME DATE,
	LOGIC_NUM INT,
	CODING_NUM INT,
	CURRENT_LOGIC_NUM INT,
	CURRENT_CODING_NUM INT
 );